# Generated by Django 4.1.4 on 2023-01-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, help_text='first_name', max_length=30, verbose_name='First Name')),
                ('lname', models.CharField(help_text='last_name', max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(help_text='Email Id', max_length=254)),
                ('password1', models.CharField(max_length=10)),
                ('password2', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('colors', models.CharField(choices=[('Pink', 'PINK'), (' ', '--SELECT--'), ('Green', 'GREEN'), ('Black', 'BLACK'), ('Red', 'RED')], max_length=10)),
            ],
        ),
    ]
